### PR TITLE
e-file: make e-file an importable module

### PR DESCRIPTION
**Pull request by Nowa-Ammerlaan**
This adds a `command-not-found` handler for Gentoo similar to those you'd find on Fedora/Ubuntu/Debian etc. It suggests first executables that closely match the input (i.e. typo suggestions), this function is borrowed from [Debian/Ubuntu](https://packages.debian.org/sid/command-not-found). Then it searches pfl using `e-file`, to accommodate this the majority of `e-file` is moved into a new module so we can inherit it.

The ebuild should install `profile.d/command-not-found.sh` into `/etc/profile.d/command-not-found.sh` for this to work. This shell file is heavily based on the one from [PackageKit](https://github.com/PackageKit/PackageKit/tree/main/contrib/command-not-found) that you'd find on [Fedora](https://packages.fedoraproject.org/pkgs/PackageKit/PackageKit-command-not-found/) systems.

This works with bash and zsh, not tested with other shells. Example output:

```
andrew@andrew-gentoo-laptop client % source profile.d/command-not-found.sh
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" apple
Command apple not found in PATH

Searching the Portage File List for packages installing apple...

No candidates found
```
```
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" pear
zsh: correct 'pear' to 'perl' [nyae]? n
Command pear not found in PATH
Maybe you meant:
ptar

Searching the Portage File List for packages installing pear...

*  dev-php/PEAR-PEAR
Seen Versions:          1.10.12 1.10.13
Portage Versions:       1.10.12 1.10.13
Repository:             gentoo
Homepage:               https://pear.php.net/package/PEAR
Description:            PEAR Base System
Matched Files:          /usr/bin/pear

```
```
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" banana
Command banana not found in PATH

Searching the Portage File List for packages installing banana...

*  sci-biology/emboss
Seen Versions:          6.6.0-r2
Portage Versions:       6.6.0-r2
Repository:             gentoo
Homepage:               http://emboss.sourceforge.net/
Description:            The European Molecular Biology Open Software Suite - A sequence analysis package
Matched Files:          /usr/bin/banana

```
```
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" shellcheck
zsh: correct 'shellcheck' to '_shellcheck' [nyae]? n
Command shellcheck not found in PATH

Searching the Portage File List for packages installing shellcheck...

*  dev-util/shellcheck
Seen Versions:          0.9.0 0.9.0-r2
Portage Versions:       0.9.0-r2
Repository:             gentoo
Homepage:               https://www.shellcheck.net/
Description:            Shell script analysis tool
Matched Files:          /usr/bin/shellcheck

```
```
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" szh
zsh: correct 'szh' to 'zsh' [nyae]? n
Command szh not found in PATH
Maybe you meant:
sh
zsh
ssh

Searching the Portage File List for packages installing szh...

No candidates found
```

Let me know what you think of this.

The changes to `e-file` I made for this to work (partially) resolve issues https://github.com/portagefilelist/client/issues/42 and https://github.com/portagefilelist/client/issues/43.

### CODE REVIEW

**Comment by Nowa-Ammerlaan** [comment]
Today's new commit adds suggestions for flatpaks and snaps as well, if `snap` and/or `flatpak` are installed on the system. Example output:

```
andrew@andrew-gentoo-laptop client % PYTHONPATH="/home/andrew/Git/client" audacity

Command "audacity" not found, but can be installed with:

sudo snap install audacity

See 'snap info <snap name>' for additional versions.


One of these flatpaks may be what you are looking for:
Audacity
Tenacity


Searching the Portage File List for packages installing audacity...

*  media-sound/audacity
Seen Versions:          3.2.5-r1 3.3.3
Portage Versions:       2.4.2-r3 3.2.5-r1 3.3.3 9999
Repository:             gentoo
Homepage:               https://www.audacityteam.org/
Description:            Free crossplatform audio editor
Matched Files:          /usr/bin/audacity

```

**Comment by bananas-repos** [comment]
Thank you for the detailed PR :-)

> The changes to e-file I made for this to work (partially) resolve issues https://github.com/portagefilelist/client/issues/42 and https://github.com/portagefilelist/client/issues/43.

I see. My Idea was the other way around, but I do see why it is done that way.

> This adds a command-not-found handler for Gentoo

I do understand the feature but I'm conflicted to see that feature should be one of pfl. I do think this command-not-found feature as a more global one. Like if you want it, install a package for it. Pfl does also not (I'm not sure since I do not use them) track flatpack installs and now suggesting them only if pfl is installed, sounds kinde of misleading.

Could it be another tool in the toolbox for portage? https://wiki.gentoo.org/wiki/Useful_Portage_tools

I'm open for discussion and maybe I will have some more questions.

**Comment by Nowa-Ammerlaan** [comment]
> I do understand the feature but I'm conflicted to see that feature should be one of pfl. I do think this command-not-found feature as a more global one. Like if you want it, install a package for it. Pfl does also not (I'm not sure since I do not use them) track flatpack installs and now suggesting them only if pfl is installed, sounds kinde of misleading.
> 
> Could it be another tool in the toolbox for portage? https://wiki.gentoo.org/wiki/Useful_Portage_tools

Yes this is a fair point. I was also wondering earlier if this should be a separate package or not. But maybe since I now added the snap/flatpak stuff this is becoming its own thing and tying it to this repository does not really make sense.

I moved the bulk of this PR to a new repository here: https://github.com/AndrewAmmerlaan/command-not-found-gentoo

It would be cool though if we can still do the rewriting of `e-file` here so I can `try: import e_file` instead of having to rely on `subprocess` and stdout capture (like I have to for snap/flatpak). I did not do the benchmarking, but my gut feeling is that import is going to be faster then creating a subprocess, especially considering that `e-file` is also written in python. What do you think?

**Comment by bananas-repos** [comment]
Wow, that was fast :-)

> I moved the bulk of this PR to a new repository here: https://github.com/AndrewAmmerlaan/command-not-found-gentoo

Good idea! 
Since I'm not yet a python expert I can only suggest an idea: Try to reduce the lookup time, since waiting for a suggestion too long will make the feature look bad. Right now a pfl search could take some time since it does a network call.

> It would be cool though if we can still do the rewriting of e-file here so I can try: import e_file instead of having to rely on subprocess and stdout capture (like I have to for snap/flatpak). I did not do the benchmarking, but my gut feeling is that import is going to be faster then creating a subprocess, especially considering that e-file is also written in python. What do you think?

Completely agree. I was confused why one was not like the other and wanted to make both scripts "look" the same.

Thank you again for your input and time!

**Comment by Nowa-Ammerlaan** [comment]
> Since I'm not yet a python expert I can only suggest an idea: Try to reduce the lookup time, since waiting for a suggestion too long will make the feature look bad. Right now a pfl search could take some time since it does a network call.

Yes ideally we would have some sort of local cache that we can search through when the network is down or slow (from what I am seeing in the code this is what Debian/Ubuntu does for `apt`). This will be a bit more work though, but I'll see what I can do.

**Comment by bananas-repos** [comment]
I've changed the target branch, since develop is the branch for further versions. There is a conflict, which is needed to be resolved.

**Comment by Nowa-Ammerlaan** [comment]
> I've changed the target branch, since develop is the branch for further versions. There is a conflict, which is needed to be resolved.

Rebased onto the `develop` branch and resolved the conflict.

**Comment by bananas-repos** [comment]
Thank you!

**Comment by Nowa-Ammerlaan** [comment]
> Thank you!

Thank you for merging!

By the way, I did the benchmark (`import` method versus `subprocess` method) and this actually does make a huge difference. Which makes sense because subproccess is going to start a new instance of python and go through our `python-exec` logic.

The "fallback" method, where we can't `import e_file.e_file`:
```
andrew@andrew-gentoo-laptop ~ % time audacity

Command "audacity" not found, but can be installed with:

sudo snap install audacity

See 'snap info <snap name>' for additional versions.


Searching the Portage File List for packages installing audacity...

*  media-sound/audacity
Seen Versions:          3.2.5-r1 3.3.3
Portage Versions:       2.4.2-r3 3.2.5-r1 3.3.3 9999
Repository:             gentoo
Homepage:               https://www.audacityteam.org/
Description:            Free crossplatform audio editor
Matched Files:          /usr/bin/audacity



audacity  1.20s user 0.14s system 72% cpu 1.850 total
```

The improved method (this PR), where we can `import e_file.e_file`:
```
andrew@andrew-gentoo-laptop ~ % time PYTHONPATH="/home/andrew/Git/client" audacity

Command "audacity" not found, but can be installed with:

sudo snap install audacity

See 'snap info <snap name>' for additional versions.


Searching the Portage File List for packages installing audacity...

*  media-sound/audacity
Seen Versions:          3.2.5-r1 3.3.3
Portage Versions:       2.4.2-r3 3.2.5-r1 3.3.3 9999
Repository:             gentoo
Homepage:               https://www.audacityteam.org/
Description:            Free crossplatform audio editor
Matched Files:          /usr/bin/audacity


PYTHONPATH="/home/andrew/Git/client" audacity  0.52s user 0.05s system 58% cpu 0.984 total
```

As a side note, I dropped the flatpak stuff because it just makes things slower and it does not really make sense because flatpaks can't be executed from `PATH` anyway (contrary to snaps, which we can simply call from `PATH`).

**Pull request merged**
