### PR TITLE
Move to setuptools and PEP517

### PR DESCRIPTION
**Pull request by parona-source**
Mostly cosmetic changes with an addition of dependencies. The ebuild already forced these changes with gpep517 other than this now going completely to pyproject.toml.

Before:
```
Archive:  dist/pfl-3.2.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-05-2023 05:04   pfl/__init__.py
     7953  10-05-2023 05:04   pfl/pfl.py
      804  10-05-2023 05:04   pfl-3.2.1.data/data/share/man/man1/pfl.1
     5563  10-05-2023 05:46   pfl-3.2.1.data/scripts/e-file
      122  10-05-2023 05:46   pfl-3.2.1.data/scripts/pfl
      462  10-05-2023 05:46   pfl-3.2.1.dist-info/METADATA
       92  10-05-2023 05:46   pfl-3.2.1.dist-info/WHEEL
        4  10-05-2023 05:46   pfl-3.2.1.dist-info/top_level.txt
      680  10-05-2023 05:46   pfl-3.2.1.dist-info/RECORD
---------                     -------
    15680                     9 files
```

After:
```
Archive:  dist/pfl-3.2.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-05-2023 05:04   pfl/__init__.py
     7953  10-05-2023 05:04   pfl/pfl.py
      804  10-05-2023 05:04   pfl-3.2.1.data/data/share/man/man1/pfl.1
     5563  10-05-2023 05:46   pfl-3.2.1.data/scripts/e-file
      122  10-05-2023 05:30   pfl-3.2.1.data/scripts/pfl
      541  10-05-2023 05:46   pfl-3.2.1.dist-info/METADATA
       92  10-05-2023 05:46   pfl-3.2.1.dist-info/WHEEL
       40  10-05-2023 05:46   pfl-3.2.1.dist-info/entry_points.txt
        4  10-05-2023 05:46   pfl-3.2.1.dist-info/top_level.txt
      771  10-05-2023 05:46   pfl-3.2.1.dist-info/RECORD
---------                     -------
    15890                     10 files
```

### CODE REVIEW

**Comment by bananas-repos** [comment]
Thank you for this PR and thank you for your time!

But first I need some clarification since I'm new to the python/ebuild world.

What does this change do exactly?
How can I verify this eg. does everything still work?
Do I need to make a new release/version bump?

Regards,
Banana

**Comment by parona-source** [comment]
> What does this change do exactly?

Biggest thing is to formally move to setuptools, distutils is deprecated in python (removed in python3.12) and only exists internally in setuptools now. [Other than that its just moving to the new:tm: way of doing it in the python world. ](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)

>  How can I verify this eg. does everything still work?

I intended to do this in a backwards compatible manor, so nothing should be different. Which is why I compare the contents of the wheel to showcase this. You can use `dev-python/build` to build sdist's and wheels to compare (so  `python -m build` and `python -m build -w`).

The only real change was removing the pfl script and using entry_points as the script was acting as one already.

To test that behavior hasn't changed I now realise that e-file doesn't behave well in an virtualenv (but that could be sorted out by updating away from old portage api), so unfortunately it would have to be installed system wide with an ebuild (ebuild doesn't need to be modified due to these changes).

To use an ebuild to test this then I'd just create an 9999 ebuild and override the repo and branch to use my version.

 > Do I need to make a new release/version bump?
 
 No, python3.12 and pep517 worked despite this with gpep517 so a new release wouldn't do much.

**Comment by parona-source** [comment]
But as I started to test it with an ebuild I get an error relating to invalid trove classifiers, so I'll look into that.

Edit: Pushed changes fixing trove classifiers, for some reason setuptools didn't complain before.

**Comment by parona-source** [comment]
Dropped the entry_points change as it had unintended side effects, now this change should 1 to 1 compatible in what is installed and where.

So updated wheel comparison

Before
```
Archive:  dist/pfl-3.2.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-05-2023 05:04   pfl/__init__.py
     7953  10-05-2023 05:04   pfl/pfl.py
      804  10-05-2023 05:04   pfl-3.2.1.data/data/share/man/man1/pfl.1
     5563  10-05-2023 05:46   pfl-3.2.1.data/scripts/e-file
      122  10-05-2023 05:46   pfl-3.2.1.data/scripts/pfl
      462  10-05-2023 05:46   pfl-3.2.1.dist-info/METADATA
       92  10-05-2023 05:46   pfl-3.2.1.dist-info/WHEEL
        4  10-05-2023 05:46   pfl-3.2.1.dist-info/top_level.txt
      680  10-05-2023 05:46   pfl-3.2.1.dist-info/RECORD
---------                     -------
    15680                     9 files
```

After
```
Archive:  dist/pfl-3.2.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-05-2023 05:04   pfl/__init__.py
     7953  10-05-2023 05:04   pfl/pfl.py
      804  10-05-2023 05:04   pfl-3.2.1.data/data/share/man/man1/pfl.1
     5563  10-05-2023 18:28   pfl-3.2.1.data/scripts/e-file
      122  10-05-2023 18:28   pfl-3.2.1.data/scripts/pfl
      572  10-05-2023 18:28   pfl-3.2.1.dist-info/METADATA
       92  10-05-2023 18:28   pfl-3.2.1.dist-info/WHEEL
        4  10-05-2023 18:28   pfl-3.2.1.dist-info/top_level.txt
      680  10-05-2023 18:28   pfl-3.2.1.dist-info/RECORD
---------                     -------
    15790                     9 files
```

**Comment by parona-source** [comment]
> To test that behavior hasn't changed I now realise that e-file doesn't behave well in an virtualenv (but that could be sorted out by updating away from old portage api)

https://github.com/portagefilelist/client/pull/28 

This should allow pfl to be installed in an virtualenv and have it work. As a bonus it should allow pfl to work for prefix users as well.

My "old portage api" hunch isn't really relevant as it appears to be only sidelined internally in portage rather than completely.

**Comment by bananas-repos** [comment]
Thank you for the clarification and also making sure everything still works.

I've changed the PR target since there are some changes already, but nothing conflicting for your PR.

Thank you again for your time and work.

Regards,
Banana

**Pull request merged**
